"""Canonical physical defaults shared by all wildfire environment entrypoints."""

DRONE_CAMERA_FOV_DEG = 90.0
DRONE_FLIGHT_LEVELS_M = (20.0, 35.0, 50.0)
DRONE_SAFETY_CLEARANCE_M = 3.0
DRONE_SPEED_MPS = 10.0
DRONE_U_MULTIPLIER = 2.25

SIM_STEP_SECONDS = 2.0

GROUND_SPEED_MPS = 1.6
GROUND_ACCEL_MPS2 = 2.0
GROUND_LIDAR_RANGE_M = 20.0
GROUND_CONFIRMATION_RANGE_M = 10.0
GROUND_ARRIVAL_SLOWDOWN_M = 10.0
GROUND_ARRIVAL_DAMPING = 0.6
