"""Generate a Plotly.js EDA report for an OmniSearch terrain cache.

Examples:

    python scripts/terrain_eda.py \
      --terrain-cache data/terrain_cache/malibu_128.npz

    python scripts/terrain_eda.py \
      --trajectory web/trajectories/nearest_candidate.json \
      --out results/eda/nearest_candidate_terrain_eda.html
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Iterable

import numpy as np


ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


PLOTLY_JS = "https://cdn.plot.ly/plotly-2.35.2.min.js"
LAND_COVER_NAMES = ["road", "open", "brush", "forest", "rock", "water"]
LAND_COVER_COLORS = ["#b59665", "#47783d", "#315a2e", "#203d24", "#555963", "#2563eb"]
OBSTACLE_NAMES = ["none", "tree", "house"]
OBSTACLE_COLORS = ["#111827", "#1d5128", "#a34d3d"]
CONTINUOUS_LAYERS = ("elevation", "slope", "moisture", "fuel_density", "rockiness")
# The planner's footprint value is camera radius, so 1.6 * radius = 0.8 * full footprint width.
DRONE_LANE_SPACING_FACTOR = 1.6


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--terrain-cache",
        default=str(ROOT / "data" / "terrain_cache" / "malibu_128.npz"),
        help="Terrain .npz cache generated by scripts/build_real_terrain_cache.py.",
    )
    p.add_argument(
        "--trajectory",
        default=None,
        help="Optional trajectory JSON. If provided, uses metadata.terrain and includes movement layers.",
    )
    p.add_argument("--out", default=None, help="Output HTML path.")
    p.add_argument("--sample-points", type=int, default=8_000, help="Max samples per box/scatter plot.")
    args = p.parse_args()

    if args.trajectory:
        terrain, source_name = _load_from_trajectory(Path(args.trajectory))
        default_stem = Path(args.trajectory).stem
    else:
        terrain, source_name = _load_from_cache(Path(args.terrain_cache))
        default_stem = Path(args.terrain_cache).stem

    out = Path(args.out) if args.out else ROOT / "results" / "eda" / f"{default_stem}_terrain_eda.html"
    generate_terrain_eda_html(
        terrain=terrain,
        source_name=source_name,
        out=out,
        sample_points=args.sample_points,
    )


def generate_terrain_eda_html(
    *,
    terrain: dict,
    source_name: str,
    out: Path,
    sample_points: int = 8_000,
) -> Path:
    _validate_terrain(terrain)
    plots = [
        _plot_land_cover_distribution(terrain),
        _plot_spatial_land_cover(terrain),
        _plot_spatial_continuous_layers(terrain),
        _plot_continuous_distributions(terrain, sample_points),
        _plot_class_conditional_layers(terrain, sample_points),
        _plot_correlation_matrix(terrain),
        _plot_obstacle_distribution(terrain),
        _plot_obstacle_by_land_cover(terrain),
        _plot_land_cover_adjacency(terrain),
    ]
    if "movement_cost" in terrain:
        plots.append(_plot_movement_cost_heatmap(terrain))
    if "speed_multiplier" in terrain:
        plots.append(_plot_speed_multiplier_heatmap(terrain))
    if "movement_cost" in terrain or "speed_multiplier" in terrain or "traversable" in terrain:
        plots.append(_plot_mobility_diagnostics(terrain, sample_points))
    if terrain.get("_frames"):
        plots.extend([
            _plot_search_difficulty_summary(terrain),
            _plot_expected_drone_lanes(terrain),
            _plot_spawn_feasibility_map(terrain),
            _plot_ugv_survivor_distances(terrain),
            _plot_traversable_components(terrain),
        ])

    summary = _summary(terrain, source_name)
    html = _build_html(summary=summary, plots=plots)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
    print(f"Wrote {out}")
    print(f"Open with: open {out}")
    return out


def _load_from_cache(path: Path) -> tuple[dict, str]:
    if not path.exists():
        raise SystemExit(f"terrain cache not found: {path}")
    with np.load(path, allow_pickle=False) as data:
        terrain = {}
        for name in (
            "land_cover",
            "elevation",
            "slope",
            "moisture",
            "fuel_density",
            "rockiness",
            "obstacle_type",
            "obstacle_height",
            "bbox",
        ):
            if name in data:
                terrain[name] = np.asarray(data[name])
        terrain["source"] = _scalar(data, "source", str(path))
        terrain["fuel_source"] = _scalar(data, "fuel_source", "unknown")
        terrain["dem_resolution_m"] = _scalar(data, "dem_resolution_m", "unknown")
        terrain["projected_crs"] = _scalar(data, "projected_crs", "unknown")
        if "metadata_json" in data:
            try:
                terrain["metadata"] = json.loads(str(data["metadata_json"].item()))
            except (ValueError, TypeError):
                terrain["metadata"] = {}
    return terrain, str(path)


def _load_from_trajectory(path: Path) -> tuple[dict, str]:
    if not path.exists():
        raise SystemExit(f"trajectory not found: {path}")
    payload = json.loads(path.read_text())
    meta = payload.get("metadata", {})
    terrain_meta = meta.get("terrain", {})
    if not terrain_meta:
        raise SystemExit("trajectory metadata does not contain terrain arrays")
    terrain = {
        "source": terrain_meta.get("source_description") or terrain_meta.get("source") or str(path),
        "metadata": terrain_meta.get("source_metadata", {}),
        "_frames": payload.get("frames", []),
        "_mission": meta,
        "_world": meta.get("world", {}),
        "_n_drones": int(meta.get("n_drones", 0)),
        "_n_ground": int(meta.get("n_ground", 0)),
        "_n_survivors": int(meta.get("n_survivors", 0)),
        "_agent_radius": float(meta.get("agent_radius", 0.04)),
    }
    for name in (
        "land_cover",
        "elevation",
        "slope",
        "moisture",
        "fuel_density",
        "rockiness",
        "obstacle_type",
        "obstacle_height",
        "movement_cost",
        "speed_multiplier",
        "traversable",
        "required_clearance",
        "required_clearance_msl",
    ):
        if name in terrain_meta:
            terrain[name] = np.asarray(terrain_meta[name])
    return terrain, str(path)


def _validate_terrain(terrain: dict) -> None:
    if "land_cover" not in terrain:
        raise SystemExit("terrain is missing land_cover")
    shape = np.asarray(terrain["land_cover"]).shape
    if len(shape) != 2:
        raise SystemExit("land_cover must be a 2D grid")
    for name in CONTINUOUS_LAYERS:
        if name not in terrain:
            raise SystemExit(f"terrain is missing {name}")
        if np.asarray(terrain[name]).shape != shape:
            raise SystemExit(f"{name} shape does not match land_cover")


def _plot_land_cover_distribution(terrain: dict) -> dict:
    cover = _land_cover(terrain)
    labels, counts, pct = _class_counts(cover, LAND_COVER_NAMES)
    traces = [
        {
            "type": "bar",
            "name": "cell count",
            "x": labels,
            "y": counts,
            "marker": {"color": LAND_COVER_COLORS[: len(labels)]},
            "customdata": pct,
            "hovertemplate": "%{x}<br>cells=%{y}<br>%{customdata:.2f}%<extra></extra>",
        },
        {
            "type": "scatter",
            "mode": "lines+markers",
            "name": "percent",
            "x": labels,
            "y": pct,
            "yaxis": "y2",
            "line": {"color": "#e6e9ef", "width": 2},
            "hovertemplate": "%{x}<br>%{y:.2f}%<extra></extra>",
        },
    ]
    return _plot(
        "land-cover-distribution",
        "Land-Cover Class Distribution",
        traces,
        {
            "xaxis": {"title": "land-cover class"},
            "yaxis": {"title": "cell count"},
            "yaxis2": {"title": "percent", "overlaying": "y", "side": "right", "range": [0, 100]},
            "legend": {"orientation": "h"},
        },
        "Basic class balance. This is the first sanity check for whether a bbox is mostly ocean, roads, brush, etc.",
    )


def _plot_spatial_land_cover(terrain: dict) -> dict:
    cover = _land_cover(terrain)
    trace = {
        "type": "heatmap",
        "z": _round_grid(np.flipud(cover)),
        "zmin": 0,
        "zmax": len(LAND_COVER_NAMES) - 1,
        "colorscale": _discrete_colorscale(LAND_COVER_COLORS),
        "colorbar": {
            "title": "land cover",
            "tickmode": "array",
            "tickvals": list(range(len(LAND_COVER_NAMES))),
            "ticktext": LAND_COVER_NAMES,
        },
        "hovertemplate": "x=%{x}<br>y=%{y}<br>class=%{z}<extra></extra>",
    }
    return _plot(
        "land-cover-map",
        "Spatial Land-Cover Map",
        [trace],
        {
            "xaxis": {"title": "grid x"},
            "yaxis": {"title": "grid y", "scaleanchor": "x"},
        },
        "Top-down class map. Hard geometric artifacts, ocean dominance, or road/building oddities are usually obvious here.",
    )


def _plot_spatial_continuous_layers(terrain: dict) -> dict:
    traces = []
    buttons = []
    for i, name in enumerate(CONTINUOUS_LAYERS):
        visible = i == 0
        traces.append({
            "type": "heatmap",
            "name": name,
            "z": _round_grid(np.flipud(_finite(terrain[name]))),
            "colorscale": "Viridis",
            "visible": visible,
            "colorbar": {"title": name},
            "hovertemplate": f"x=%{{x}}<br>y=%{{y}}<br>{name}=%{{z:.3f}}<extra></extra>",
        })
        buttons.append({
            "label": name,
            "method": "update",
            "args": [
                {"visible": [j == i for j in range(len(CONTINUOUS_LAYERS))]},
                {"title": f"Spatial {name.replace('_', ' ').title()} Map"},
            ],
        })
    return _plot(
        "continuous-spatial-maps",
        "Spatial Elevation / Slope / Fuel / Moisture / Rockiness Maps",
        traces,
        {
            "xaxis": {"title": "grid x"},
            "yaxis": {"title": "grid y", "scaleanchor": "x"},
            "updatemenus": [{"buttons": buttons, "direction": "right", "x": 0, "y": 1.14}],
        },
        "Use the buttons to inspect each continuous terrain field spatially.",
    )


def _plot_continuous_distributions(terrain: dict, sample_points: int) -> dict:
    cover = _land_cover(terrain)
    land_mask = cover != 5
    traces = []
    for i, name in enumerate(CONTINUOUS_LAYERS):
        values = _sample(_finite(terrain[name])[land_mask], sample_points)
        traces.append({
            "type": "histogram",
            "name": name,
            "x": _round_list(values),
            "opacity": 0.68,
            "nbinsx": 45,
            "marker": {"color": LAND_COVER_COLORS[(i + 1) % len(LAND_COVER_COLORS)]},
        })
    return _plot(
        "continuous-distributions",
        "Continuous Terrain-Layer Distributions",
        traces,
        {
            "barmode": "overlay",
            "xaxis": {"title": "normalized layer value"},
            "yaxis": {"title": "cell count"},
        },
        "Histograms are sampled from non-water cells when water exists, because water can dominate moisture/fuel statistics.",
    )


def _plot_class_conditional_layers(terrain: dict, sample_points: int) -> dict:
    cover = _land_cover(terrain)
    traces = []
    for i, name in enumerate(CONTINUOUS_LAYERS):
        x = []
        y = []
        values = _finite(terrain[name])
        for cover_id, cover_name in enumerate(LAND_COVER_NAMES):
            mask = cover == cover_id
            sampled = _sample(values[mask], max(sample_points // len(CONTINUOUS_LAYERS), 1))
            x.extend([cover_name] * len(sampled))
            y.extend(_round_list(sampled))
        traces.append({
            "type": "box",
            "name": name,
            "x": x,
            "y": y,
            "boxpoints": "outliers",
            "marker": {"color": LAND_COVER_COLORS[i % len(LAND_COVER_COLORS)]},
        })
    return _plot(
        "class-conditional-layers",
        "Terrain Layers by Land-Cover Class",
        traces,
        {
            "xaxis": {"title": "land-cover class"},
            "yaxis": {"title": "layer value"},
            "boxmode": "group",
        },
        "Checks whether the class semantics line up with the continuous fields, for example forest/brush having higher fuel.",
    )


def _plot_correlation_matrix(terrain: dict) -> dict:
    layers = [name for name in CONTINUOUS_LAYERS if name in terrain]
    for optional in ("movement_cost", "speed_multiplier"):
        if optional in terrain:
            layers.append(optional)
    arrays = []
    for name in layers:
        arrays.append(_finite(terrain[name]).reshape(-1))
    corr = np.corrcoef(np.asarray(arrays))
    trace = {
        "type": "heatmap",
        "x": layers,
        "y": layers,
        "z": _round_grid(corr),
        "zmin": -1,
        "zmax": 1,
        "colorscale": "RdBu",
        "reversescale": True,
        "colorbar": {"title": "corr"},
        "text": _round_grid(corr),
        "hovertemplate": "%{y} vs %{x}<br>corr=%{z:.3f}<extra></extra>",
    }
    return _plot(
        "terrain-correlations",
        "Terrain Layer Correlation Matrix",
        [trace],
        {"xaxis": {"side": "bottom"}, "yaxis": {"autorange": "reversed"}},
        "Useful for spotting accidental coupling, for example fuel_density tracking elevation too strongly.",
    )


def _plot_obstacle_distribution(terrain: dict) -> dict:
    if "obstacle_type" not in terrain:
        return _empty_plot("obstacle-distribution", "Obstacle Distribution", "No obstacle_type grid found.")
    obstacle = np.asarray(terrain["obstacle_type"], dtype=int)
    labels, counts, pct = _class_counts(obstacle, OBSTACLE_NAMES)
    traces = [
        {
            "type": "bar",
            "x": labels,
            "y": counts,
            "customdata": pct,
            "marker": {"color": OBSTACLE_COLORS[: len(labels)]},
            "hovertemplate": "%{x}<br>cells=%{y}<br>%{customdata:.2f}%<extra></extra>",
        }
    ]
    if "obstacle_height" in terrain and np.count_nonzero(obstacle) > 0:
        heights = _finite(terrain["obstacle_height"])[obstacle != 0]
        traces.append({
            "type": "histogram",
            "name": "obstacle height",
            "x": _round_list(heights),
            "yaxis": "y2",
            "opacity": 0.55,
            "marker": {"color": "#60a5fa"},
            "nbinsx": 25,
        })
    return _plot(
        "obstacle-distribution",
        "Obstacle Distribution and Heights",
        traces,
        {
            "xaxis": {"title": "obstacle class"},
            "yaxis": {"title": "cell count"},
            "yaxis2": {"title": "height histogram count", "overlaying": "y", "side": "right"},
            "showlegend": False,
        },
        "Counts tree and house obstacle cells. If houses are common outside road/open areas, that is suspicious.",
    )


def _plot_obstacle_by_land_cover(terrain: dict) -> dict:
    if "obstacle_type" not in terrain:
        return _empty_plot("obstacle-by-cover", "Obstacle by Land Cover", "No obstacle_type grid found.")
    cover = _land_cover(terrain)
    obstacle = np.asarray(terrain["obstacle_type"], dtype=int)
    matrix = np.zeros((len(OBSTACLE_NAMES), len(LAND_COVER_NAMES)), dtype=int)
    for oi in range(len(OBSTACLE_NAMES)):
        for ci in range(len(LAND_COVER_NAMES)):
            matrix[oi, ci] = int(np.count_nonzero((obstacle == oi) & (cover == ci)))
    trace = {
        "type": "heatmap",
        "x": LAND_COVER_NAMES,
        "y": OBSTACLE_NAMES,
        "z": matrix.tolist(),
        "colorscale": "Blues",
        "colorbar": {"title": "cells"},
        "hovertemplate": "%{y} on %{x}<br>cells=%{z}<extra></extra>",
    }
    return _plot(
        "obstacle-by-cover",
        "Obstacle Cells by Land-Cover Class",
        [trace],
        {},
        "Cross-tab of object placement against land cover. This catches houses in forests/water and trees on roads.",
    )


def _plot_land_cover_adjacency(terrain: dict) -> dict:
    cover = _land_cover(terrain)
    matrix = np.zeros((len(LAND_COVER_NAMES), len(LAND_COVER_NAMES)), dtype=int)
    pairs = [
        (cover[:, :-1], cover[:, 1:]),
        (cover[:-1, :], cover[1:, :]),
    ]
    for left, right in pairs:
        for a, b in zip(left.reshape(-1), right.reshape(-1)):
            ai = int(a)
            bi = int(b)
            if 0 <= ai < len(LAND_COVER_NAMES) and 0 <= bi < len(LAND_COVER_NAMES) and ai != bi:
                matrix[ai, bi] += 1
                matrix[bi, ai] += 1
    trace = {
        "type": "heatmap",
        "x": LAND_COVER_NAMES,
        "y": LAND_COVER_NAMES,
        "z": matrix.tolist(),
        "colorscale": "Magma",
        "colorbar": {"title": "neighbor boundaries"},
        "hovertemplate": "%{y} next to %{x}<br>boundaries=%{z}<extra></extra>",
    }
    return _plot(
        "land-cover-adjacency",
        "Land-Cover Boundary / Adjacency Matrix",
        [trace],
        {},
        "Counts neighboring cells of different classes. Very high boundary counts can indicate noisy, fragmented terrain.",
    )


def _plot_movement_cost_heatmap(terrain: dict) -> dict:
    cost = _finite(terrain["movement_cost"])
    trace = {
        "type": "heatmap",
        "z": _round_grid(np.flipud(cost)),
        "colorscale": "Inferno",
        "colorbar": {"title": "cost"},
        "hovertemplate": "x=%{x}<br>y=%{y}<br>movement cost=%{z:.3f}<extra></extra>",
    }
    return _plot(
        "movement-cost-heatmap",
        "Movement Cost Heatmap",
        [trace],
        {
            "xaxis": {"title": "grid x"},
            "yaxis": {"title": "grid y", "scaleanchor": "x"},
        },
        "Spatial ground movement cost used by UGV reward/path diagnostics. Higher values mean more expensive terrain.",
    )


def _plot_speed_multiplier_heatmap(terrain: dict) -> dict:
    speed = _finite(terrain["speed_multiplier"])
    trace = {
        "type": "heatmap",
        "z": _round_grid(np.flipud(speed)),
        "zmin": 0.0,
        "zmax": 1.0,
        "colorscale": "Viridis",
        "colorbar": {"title": "speed"},
        "hovertemplate": "x=%{x}<br>y=%{y}<br>speed multiplier=%{z:.3f}<extra></extra>",
    }
    return _plot(
        "speed-multiplier-heatmap",
        "Speed Multiplier Heatmap",
        [trace],
        {
            "xaxis": {"title": "grid x"},
            "yaxis": {"title": "grid y", "scaleanchor": "x"},
        },
        "Spatial ground speed multiplier. Zero means blocked/non-traversable; one means full nominal UGV speed.",
    )


def _plot_mobility_diagnostics(terrain: dict, sample_points: int) -> dict:
    cover = _land_cover(terrain)
    traces = []
    if "movement_cost" in terrain:
        cost = _finite(terrain["movement_cost"])
        x = []
        y = []
        for cover_id, cover_name in enumerate(LAND_COVER_NAMES):
            sampled = _sample(cost[cover == cover_id], max(sample_points // len(LAND_COVER_NAMES), 1))
            x.extend([cover_name] * len(sampled))
            y.extend(_round_list(sampled))
        traces.append({
            "type": "box",
            "name": "movement cost",
            "x": x,
            "y": y,
            "boxpoints": "outliers",
            "marker": {"color": "#60a5fa"},
        })
    if "speed_multiplier" in terrain:
        speed = _finite(terrain["speed_multiplier"])
        x = []
        y = []
        for cover_id, cover_name in enumerate(LAND_COVER_NAMES):
            sampled = _sample(speed[cover == cover_id], max(sample_points // len(LAND_COVER_NAMES), 1))
            x.extend([cover_name] * len(sampled))
            y.extend(_round_list(sampled))
        traces.append({
            "type": "box",
            "name": "speed multiplier",
            "x": x,
            "y": y,
            "boxpoints": "outliers",
            "marker": {"color": "#22c55e"},
        })
    if "traversable" in terrain:
        traversable = np.asarray(terrain["traversable"], dtype=bool)
        labels = []
        pct = []
        for cover_id, cover_name in enumerate(LAND_COVER_NAMES):
            mask = cover == cover_id
            labels.append(cover_name)
            pct.append(round(float(100.0 * traversable[mask].mean()) if np.any(mask) else 0.0, 4))
        traces.append({
            "type": "scatter",
            "mode": "lines+markers",
            "name": "traversable %",
            "x": labels,
            "y": pct,
            "yaxis": "y2",
            "line": {"color": "#fbbf24", "width": 3},
        })
    return _plot(
        "mobility-diagnostics",
        "Ground Mobility Diagnostics by Land Cover",
        traces,
        {
            "xaxis": {"title": "land-cover class"},
            "yaxis": {"title": "movement cost / speed multiplier"},
            "yaxis2": {"title": "traversable (%)", "overlaying": "y", "side": "right", "range": [0, 100]},
            "legend": {"orientation": "h"},
        },
        "Available when the input is a trajectory JSON, because movement/traversability are scenario-derived layers.",
    )


def _plot_search_difficulty_summary(terrain: dict) -> dict:
    metrics = _search_difficulty_metrics(terrain)
    labels = [
        "searchable area",
        "spawn-feasible area",
        "UGV traversable area",
        "largest connected component",
    ]
    values = [
        metrics["searchable_fraction"],
        metrics["spawn_feasible_fraction"],
        metrics["traversable_fraction"],
        metrics["largest_component_fraction"],
    ]
    hover = [
        "non-water and non-rock cells considered by the drone lawnmower policy",
        "cells where survivor/start placement is feasible",
        "cells traversable by UGVs after slope/obstacle/water/rock blocking",
        "largest traversable connected component as a fraction of all cells",
    ]
    traces = [{
        "type": "bar",
        "x": labels,
        "y": [round(100.0 * v, 4) for v in values],
        "customdata": hover,
        "marker": {"color": ["#60a5fa", "#22c55e", "#fbbf24", "#a855f7"]},
        "hovertemplate": "%{x}<br>%{y:.2f}%<br>%{customdata}<extra></extra>",
    }]
    annotations = [
        {
            "xref": "paper",
            "yref": "paper",
            "x": 0.01,
            "y": 1.12 - i * 0.07,
            "showarrow": False,
            "align": "left",
            "font": {"size": 12, "color": "#e6e9ef"},
            "text": text,
        }
        for i, text in enumerate([
            f"Expected drone lanes: {metrics['lane_count']} "
            f"({metrics['lanes_per_drone']:.2f} per drone)",
            f"Spawn feasible / survivor: {metrics['feasible_per_survivor']:.1f} cells",
            f"Traversable components: {metrics['component_count']}",
        ])
    ]
    return _plot(
        "search-difficulty-summary",
        "Search Difficulty Summary",
        traces,
        {
            "yaxis": {"title": "fraction of grid (%)", "range": [0, 100]},
            "annotations": annotations,
            "margin": {"l": 70, "r": 70, "t": 135, "b": 90},
            "showlegend": False,
        },
        "High-level search difficulty metrics from the trajectory terrain and initial mission layout.",
    )


def _plot_expected_drone_lanes(terrain: dict) -> dict:
    lanes, info = _expected_lawnmower_lanes(terrain)
    blocks = _balanced_lane_blocks(lanes, max(int(terrain.get("_n_drones", 0)), 1))
    traces = [{
        "type": "bar",
        "name": "searchable cells per lane",
        "x": [f"lane {i}" for i in range(len(lanes))],
        "y": [round(float(lane["weight"]), 4) for lane in lanes],
        "marker": {"color": "#60a5fa"},
        "hovertemplate": "%{x}<br>searchable cells=%{y}<extra></extra>",
    }]
    if blocks:
        x = []
        y = []
        for drone_idx, block in enumerate(blocks):
            x.append(f"drone {drone_idx}")
            y.append(sum(float(lane["weight"]) for lane in block))
        traces.append({
            "type": "bar",
            "name": "assigned lane workload",
            "x": x,
            "y": [round(v, 4) for v in y],
            "marker": {"color": "#22c55e"},
            "xaxis": "x2",
            "yaxis": "y2",
            "hovertemplate": "%{x}<br>assigned cells=%{y}<extra></extra>",
        })
    annotations = [{
        "xref": "paper",
        "yref": "paper",
        "x": 0.01,
        "y": 1.15,
        "showarrow": False,
        "align": "left",
        "font": {"size": 12, "color": "#e6e9ef"},
        "text": (
            f"footprint={info['footprint']:.3f}, lane spacing={info['lane_spacing']:.3f}, "
            f"candidate lanes={info['candidate_lane_count']}, non-empty lanes={len(lanes)}"
        ),
    }]
    return _plot(
        "expected-drone-lanes",
        "Expected Drone Lane Count and Workload",
        traces,
        {
            "grid": {"rows": 1, "columns": 2, "pattern": "independent"},
            "xaxis": {"title": "lawnmower lane", "domain": [0.0, 0.62]},
            "yaxis": {"title": "searchable cells"},
            "xaxis2": {"title": "drone", "domain": [0.72, 1.0]},
            "yaxis2": {"title": "assigned cells", "anchor": "x2"},
            "annotations": annotations,
            "margin": {"l": 70, "r": 70, "t": 125, "b": 90},
            "legend": {"orientation": "h"},
        },
        "Mirrors the lawnmower policy geometry: ocean/water and rock do not contribute search workload.",
    )


def _plot_spawn_feasibility_map(terrain: dict) -> dict:
    feasible = _spawn_feasible_mask(terrain)
    frame0 = _initial_frame(terrain)
    traces = [{
        "type": "heatmap",
        "name": "spawn feasible",
        "z": _round_grid(np.flipud(feasible.astype(float))),
        "zmin": 0,
        "zmax": 1,
        "colorscale": [[0, "#111827"], [0.49, "#111827"], [0.5, "#22c55e"], [1, "#22c55e"]],
        "colorbar": {"title": "feasible"},
        "hovertemplate": "x=%{x}<br>y=%{y}<br>feasible=%{z}<extra></extra>",
    }]
    survivors = frame0.get("survivors", [])
    if survivors:
        sx, sy = _world_points_to_grid(terrain, [(s["x"], s["y"]) for s in survivors])
        traces.append({
            "type": "scatter",
            "mode": "markers",
            "name": "survivors",
            "x": sx,
            "y": sy,
            "marker": {"symbol": "x", "size": 11, "color": "#ef4444", "line": {"width": 2}},
            "hovertemplate": "survivor<br>x=%{x:.1f}<br>y=%{y:.1f}<extra></extra>",
        })
    ground = [a for a in frame0.get("agents", []) if a.get("type") == "ground"]
    if ground:
        gx, gy = _world_points_to_grid(terrain, [(a["x"], a["y"]) for a in ground])
        traces.append({
            "type": "scatter",
            "mode": "markers",
            "name": "UGV starts",
            "x": gx,
            "y": gy,
            "marker": {"symbol": "square", "size": 10, "color": "#14b8a6"},
            "hovertemplate": "UGV start<br>x=%{x:.1f}<br>y=%{y:.1f}<extra></extra>",
        })
    return _plot(
        "spawn-feasibility-map",
        "Survivor Spawn Feasibility Map",
        traces,
        {
            "xaxis": {"title": "grid x"},
            "yaxis": {"title": "grid y", "scaleanchor": "x"},
            "legend": {"orientation": "h"},
        },
        "Feasible cells use the scenario's traversability layer when available; survivors and UGV starts are from frame 0.",
    )


def _plot_ugv_survivor_distances(terrain: dict) -> dict:
    frame0 = _initial_frame(terrain)
    ground = [a for a in frame0.get("agents", []) if a.get("type") == "ground"]
    survivors = frame0.get("survivors", [])
    if not ground or not survivors:
        return _empty_plot(
            "ugv-survivor-distance",
            "Distance from UGV Starts to Survivors",
            "No frame-0 UGV starts or survivor positions found in the trajectory.",
        )
    matrix = np.zeros((len(ground), len(survivors)), dtype=float)
    for gi, agent in enumerate(ground):
        for si, survivor in enumerate(survivors):
            dx = float(agent["x"]) - float(survivor["x"])
            dy = float(agent["y"]) - float(survivor["y"])
            matrix[gi, si] = math.hypot(dx, dy)
    traces = [
        {
            "type": "heatmap",
            "x": [f"survivor {i}" for i in range(len(survivors))],
            "y": [a.get("name", f"ground {i}") for i, a in enumerate(ground)],
            "z": _round_grid(matrix),
            "colorscale": "Viridis",
            "colorbar": {"title": "distance"},
            "hovertemplate": "%{y} to %{x}<br>distance=%{z:.3f}<extra></extra>",
        },
        {
            "type": "bar",
            "name": "nearest UGV distance",
            "x": [f"survivor {i}" for i in range(len(survivors))],
            "y": _round_list(matrix.min(axis=0)),
            "xaxis": "x2",
            "yaxis": "y2",
            "marker": {"color": "#fbbf24"},
            "hovertemplate": "%{x}<br>nearest distance=%{y:.3f}<extra></extra>",
        },
    ]
    return _plot(
        "ugv-survivor-distance",
        "Distance from UGV Starts to Survivors",
        traces,
        {
            "grid": {"rows": 1, "columns": 2, "pattern": "independent"},
            "xaxis": {"domain": [0.0, 0.58]},
            "yaxis": {"title": "UGV start"},
            "xaxis2": {"title": "survivor", "domain": [0.68, 1.0]},
            "yaxis2": {"title": "nearest distance", "anchor": "x2"},
        },
        "Straight-line start distance. It does not include route detours from blocked terrain or fire.",
    )


def _plot_traversable_components(terrain: dict) -> dict:
    labels, sizes = _connected_components(_traversable_mask(terrain))
    component_count = len(sizes)
    display = labels.astype(float)
    display[display < 0] = np.nan
    top = sorted(enumerate(sizes), key=lambda item: item[1], reverse=True)[:12]
    traces = [
        {
            "type": "heatmap",
            "name": "component map",
            "z": _round_grid(np.flipud(display)),
            "colorscale": "Turbo",
            "colorbar": {"title": "component"},
            "hovertemplate": "x=%{x}<br>y=%{y}<br>component=%{z}<extra></extra>",
        },
        {
            "type": "bar",
            "name": "component sizes",
            "x": [f"component {idx}" for idx, _ in top],
            "y": [int(size) for _, size in top],
            "xaxis": "x2",
            "yaxis": "y2",
            "marker": {"color": "#a855f7"},
            "hovertemplate": "%{x}<br>cells=%{y}<extra></extra>",
        },
    ]
    return _plot(
        "traversable-components",
        "Connected Components of Traversable Land",
        traces,
        {
            "grid": {"rows": 1, "columns": 2, "pattern": "independent"},
            "xaxis": {"title": "grid x", "domain": [0.0, 0.58]},
            "yaxis": {"title": "grid y", "scaleanchor": "x", "anchor": "x"},
            "xaxis2": {"title": "component", "domain": [0.68, 1.0]},
            "yaxis2": {"title": "cells", "anchor": "x2"},
            "annotations": [{
                "xref": "paper",
                "yref": "paper",
                "x": 0.01,
                "y": 1.12,
                "showarrow": False,
                "align": "left",
                "font": {"size": 12, "color": "#e6e9ef"},
                "text": f"{component_count} traversable connected components",
            }],
            "margin": {"l": 70, "r": 70, "t": 115, "b": 80},
        },
        "4-neighbor connected components over UGV-traversable land. Many small islands mean harder routing.",
    )


def _summary(terrain: dict, source_name: str) -> dict:
    cover = _land_cover(terrain)
    total = int(cover.size)
    water = int(np.count_nonzero(cover == 5))
    road = int(np.count_nonzero(cover == 0))
    obstacle_count = int(np.count_nonzero(np.asarray(terrain.get("obstacle_type", np.zeros_like(cover))) != 0))
    summary = {
        "source": source_name,
        "grid": f"{cover.shape[1]} x {cover.shape[0]}",
        "total cells": total,
        "water cells": f"{water} ({100.0 * water / total:.2f}%)",
        "road cells": f"{road} ({100.0 * road / total:.2f}%)",
        "obstacle cells": f"{obstacle_count} ({100.0 * obstacle_count / total:.2f}%)",
        "fuel source": terrain.get("fuel_source", "unknown"),
        "DEM resolution": terrain.get("dem_resolution_m", "unknown"),
        "CRS": terrain.get("projected_crs", "unknown"),
    }
    if "bbox" in terrain:
        bbox = np.asarray(terrain["bbox"]).reshape(-1)
        if len(bbox) == 4:
            summary["bbox"] = ", ".join(f"{float(v):.5f}" for v in bbox)
    metadata = terrain.get("metadata", {})
    source_description = metadata.get("source_description") or terrain.get("source")
    if source_description:
        summary["description"] = source_description
    if terrain.get("_frames"):
        metrics = _search_difficulty_metrics(terrain)
        summary["searchable area"] = f"{100.0 * metrics['searchable_fraction']:.2f}%"
        summary["expected drone lanes"] = metrics["lane_count"]
        summary["spawn feasible cells"] = (
            f"{metrics['spawn_feasible_cells']} "
            f"({100.0 * metrics['spawn_feasible_fraction']:.2f}%)"
        )
        summary["traversable components"] = metrics["component_count"]
    return summary


def _search_difficulty_metrics(terrain: dict) -> dict:
    cover = _land_cover(terrain)
    total = max(int(cover.size), 1)
    searchable = _searchable_mask(terrain)
    spawn_feasible = _spawn_feasible_mask(terrain)
    traversable = _traversable_mask(terrain)
    _, component_sizes = _connected_components(traversable)
    lanes, _ = _expected_lawnmower_lanes(terrain)
    n_drones = max(int(terrain.get("_n_drones", 0)), 1)
    n_survivors = max(int(terrain.get("_n_survivors", 0)), 1)
    largest = max(component_sizes) if component_sizes else 0
    return {
        "searchable_fraction": float(searchable.mean()),
        "spawn_feasible_fraction": float(spawn_feasible.mean()),
        "traversable_fraction": float(traversable.mean()),
        "largest_component_fraction": float(largest / total),
        "component_count": len(component_sizes),
        "lane_count": len(lanes),
        "lanes_per_drone": float(len(lanes) / n_drones),
        "spawn_feasible_cells": int(spawn_feasible.sum()),
        "feasible_per_survivor": float(spawn_feasible.sum() / n_survivors),
    }


def _searchable_mask(terrain: dict) -> np.ndarray:
    cover = _land_cover(terrain)
    return (cover != 5) & (cover != 4)


def _spawn_feasible_mask(terrain: dict) -> np.ndarray:
    if "traversable" in terrain:
        return np.asarray(terrain["traversable"], dtype=bool)
    cover = _land_cover(terrain)
    obstacle = np.asarray(terrain.get("obstacle_type", np.zeros_like(cover)), dtype=int)
    return _searchable_mask(terrain) & (obstacle == 0)


def _traversable_mask(terrain: dict) -> np.ndarray:
    if "traversable" in terrain:
        return np.asarray(terrain["traversable"], dtype=bool)
    return _spawn_feasible_mask(terrain)


def _initial_frame(terrain: dict) -> dict:
    frames = terrain.get("_frames") or []
    return frames[0] if frames else {}


def _world_points_to_grid(terrain: dict, points: list[tuple[float, float]]) -> tuple[list[float], list[float]]:
    cover = _land_cover(terrain)
    height, width = cover.shape
    world = terrain.get("_world", {})
    x_semidim = float(world.get("x_semidim", 1.0))
    y_semidim = float(world.get("y_semidim", 1.0))
    xs = []
    ys = []
    for x, y in points:
        gx = (float(x) + x_semidim) / (2.0 * x_semidim) * width
        gy = (float(y) + y_semidim) / (2.0 * y_semidim) * height
        xs.append(round(min(max(gx, 0.0), width - 1.0), 3))
        ys.append(round(min(max(gy, 0.0), height - 1.0), 3))
    return xs, ys


def _expected_lawnmower_lanes(terrain: dict) -> tuple[list[dict], dict]:
    cover = _land_cover(terrain)
    size_y, size_x = cover.shape
    mission = terrain.get("_mission", {})
    world = terrain.get("_world", {})
    x_semidim = float(world.get("x_semidim", 1.0))
    y_semidim = float(world.get("y_semidim", 1.0))
    agent_radius = float(terrain.get("_agent_radius", 0.04))
    flight_levels = mission.get("terrain", {}).get("drone_flight_levels", [])
    fov_deg = float(mission.get("terrain", {}).get("drone_camera_fov_deg", 65.0))
    min_altitude = min(float(v) for v in flight_levels) if flight_levels else 0.18
    footprint = max(min_altitude * math.tan(math.radians(fov_deg) / 2.0), 1e-6)
    lane_spacing = footprint * DRONE_LANE_SPACING_FACTOR

    margin = max(agent_radius, 0.02)
    x_min_world = -x_semidim + margin
    x_max_world = x_semidim - margin
    y_min_world = -y_semidim + margin
    y_max_world = y_semidim - margin
    span_y = max(y_max_world - y_min_world, 1e-6)
    candidate_lane_count = max(1, int(math.ceil(span_y / lane_spacing)) + 1)
    lane_ys = np.linspace(y_min_world, y_max_world, candidate_lane_count)

    cell_w = 2.0 * x_semidim / size_x
    cell_h = 2.0 * y_semidim / size_y
    cell_xs = np.linspace(-x_semidim + 0.5 * cell_w, x_semidim - 0.5 * cell_w, size_x)
    cell_ys = np.linspace(-y_semidim + 0.5 * cell_h, y_semidim - 0.5 * cell_h, size_y)
    searchable = _searchable_mask(terrain)

    lanes: list[dict] = []
    for lane_y in lane_ys:
        y_mask = np.abs(cell_ys - lane_y) <= lane_spacing * 0.5
        lane_mask = searchable & y_mask.reshape(size_y, 1)
        weight = int(lane_mask.sum())
        if weight <= 0:
            continue
        x_used = lane_mask.any(axis=0)
        used_indices = np.flatnonzero(x_used)
        segment_margin = max(0.5 * footprint, 0.5 * cell_w)
        lanes.append({
            "y": float(lane_y),
            "x_min": max(x_min_world, float(cell_xs[int(used_indices.min())]) - segment_margin),
            "x_max": min(x_max_world, float(cell_xs[int(used_indices.max())]) + segment_margin),
            "weight": float(weight),
        })
    if not lanes:
        lanes = [
            {"y": float(y), "x_min": x_min_world, "x_max": x_max_world, "weight": 1.0}
            for y in lane_ys
        ]
    return lanes, {
        "footprint": footprint,
        "lane_spacing": lane_spacing,
        "candidate_lane_count": candidate_lane_count,
    }


def _balanced_lane_blocks(lanes: list[dict], n_drones: int) -> list[list[dict]]:
    n_drones = max(int(n_drones), 1)
    blocks: list[list[dict]] = []
    start = 0
    remaining_weight = sum(float(lane["weight"]) for lane in lanes)
    for drone_idx in range(n_drones):
        remaining_drones = n_drones - drone_idx
        if start >= len(lanes):
            blocks.append([])
            continue
        if remaining_drones == 1:
            blocks.append(lanes[start:])
            break
        target = remaining_weight / remaining_drones
        end = start
        acc = 0.0
        max_end = len(lanes) - (remaining_drones - 1)
        while end < max_end:
            next_acc = acc + float(lanes[end]["weight"])
            if acc > 0 and abs(next_acc - target) > abs(acc - target):
                break
            acc = next_acc
            end += 1
            if acc >= target:
                break
        if end == start:
            acc = float(lanes[end]["weight"])
            end += 1
        blocks.append(lanes[start:end])
        remaining_weight -= acc
        start = end
    while len(blocks) < n_drones:
        blocks.append([])
    return blocks


def _connected_components(mask: np.ndarray) -> tuple[np.ndarray, list[int]]:
    mask = np.asarray(mask, dtype=bool)
    labels = np.full(mask.shape, -1, dtype=int)
    sizes: list[int] = []
    component = 0
    height, width = mask.shape
    for y in range(height):
        for x in range(width):
            if not mask[y, x] or labels[y, x] >= 0:
                continue
            stack = [(x, y)]
            labels[y, x] = component
            size = 0
            while stack:
                cx, cy = stack.pop()
                size += 1
                for nx, ny in ((cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1)):
                    if 0 <= nx < width and 0 <= ny < height and mask[ny, nx] and labels[ny, nx] < 0:
                        labels[ny, nx] = component
                        stack.append((nx, ny))
            sizes.append(size)
            component += 1
    return labels, sizes


def _plot(plot_id: str, title: str, data: list[dict], layout: dict, description: str) -> dict:
    base_layout = {
        "title": title,
        "paper_bgcolor": "#10141d",
        "plot_bgcolor": "#10141d",
        "font": {"color": "#e6e9ef"},
        "margin": {"l": 70, "r": 70, "t": 70, "b": 70},
    }
    return {
        "id": plot_id,
        "title": title,
        "description": description,
        "data": data,
        "layout": {**base_layout, **layout},
    }


def _empty_plot(plot_id: str, title: str, description: str) -> dict:
    return _plot(plot_id, title, [], {}, description)


def _build_html(*, summary: dict, plots: list[dict]) -> str:
    cards = "\n".join(
        f"""
<section class="card">
  <div id="{_escape_html(plot['id'])}" class="plot"></div>
  <p>{_escape_html(plot['description'])}</p>
</section>
"""
        for plot in plots
    )
    summary_rows = "\n".join(
        f"<tr><th>{_escape_html(str(key))}</th><td>{_escape_html(str(value))}</td></tr>"
        for key, value in summary.items()
    )
    payload = {"plots": plots}
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Terrain EDA</title>
<script src="{PLOTLY_JS}"></script>
<style>
  :root {{
    --bg: #0e1118;
    --panel: #151a23;
    --border: #263043;
    --text: #e6e9ef;
    --muted: #9aa5ba;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    background: var(--bg);
    color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", sans-serif;
  }}
  header {{
    padding: 24px 28px 12px;
    border-bottom: 1px solid var(--border);
    background: var(--panel);
  }}
  h1 {{ margin: 0 0 8px; font-size: 24px; }}
  .subtitle {{ color: var(--muted); }}
  main {{ padding: 22px 28px 40px; display: grid; gap: 22px; }}
  .card {{
    border: 1px solid var(--border);
    border-radius: 12px;
    background: var(--panel);
    padding: 16px;
  }}
  .plot {{ width: 100%; height: 560px; }}
  p {{ color: var(--muted); margin: 10px 4px 0; line-height: 1.45; }}
  table {{ border-collapse: collapse; margin-top: 14px; max-width: 1100px; }}
  th, td {{ padding: 6px 16px 6px 0; text-align: left; border-bottom: 1px solid var(--border); }}
  th {{ color: var(--muted); font-weight: 500; white-space: nowrap; }}
</style>
</head>
<body>
<header>
  <h1>Terrain EDA</h1>
  <div class="subtitle">Class distribution, spatial fields, obstacles, and terrain-layer diagnostics.</div>
  <table>{summary_rows}</table>
</header>
<main>
{cards}
</main>
<script>
const payload = {json.dumps(payload, separators=(",", ":"))};
for (const plot of payload.plots) {{
  Plotly.newPlot(plot.id, plot.data, plot.layout, {{responsive: true}});
}}
</script>
</body>
</html>
"""


def _land_cover(terrain: dict) -> np.ndarray:
    return np.asarray(terrain["land_cover"], dtype=int)


def _class_counts(values: np.ndarray, names: list[str]) -> tuple[list[str], list[int], list[float]]:
    total = max(int(values.size), 1)
    labels = []
    counts = []
    pct = []
    for idx, name in enumerate(names):
        count = int(np.count_nonzero(values == idx))
        labels.append(name)
        counts.append(count)
        pct.append(round(float(100.0 * count / total), 4))
    return labels, counts, pct


def _discrete_colorscale(colors: list[str]) -> list[list[float | str]]:
    max_value = len(colors) - 1
    stops: list[list[float | str]] = []
    for idx, color in enumerate(colors):
        lo = max(0.0, (idx - 0.5) / max_value)
        hi = min(1.0, (idx + 0.5) / max_value)
        stops.append([lo, color])
        stops.append([hi, color])
    return stops


def _finite(array: np.ndarray) -> np.ndarray:
    array = np.asarray(array, dtype=float)
    fill = float(np.nanmean(array)) if np.isfinite(array).any() else 0.0
    return np.nan_to_num(array, nan=fill, posinf=fill, neginf=fill)


def _sample(values: np.ndarray, max_points: int) -> np.ndarray:
    values = np.asarray(values, dtype=float).reshape(-1)
    values = values[np.isfinite(values)]
    if max_points <= 0 or len(values) <= max_points:
        return values
    idx = np.linspace(0, len(values) - 1, max_points, dtype=int)
    return values[idx]


def _round_grid(array: np.ndarray) -> list[list[float]]:
    return [[round(float(value), 4) for value in row] for row in np.asarray(array).tolist()]


def _round_list(values: Iterable[float]) -> list[float]:
    out = []
    for value in values:
        value = float(value)
        if math.isfinite(value):
            out.append(round(value, 4))
    return out


def _scalar(data, key: str, default):
    if key not in data:
        return default
    value = data[key]
    try:
        return value.item()
    except ValueError:
        return value.tolist()


def _escape_html(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


if __name__ == "__main__":
    main()
